# Generated by Django 6.0.1 on 2026-02-27 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('material', models.ForeignKey(db_column='material_id', on_delete=django.db.models.deletion.CASCADE, to='materials.material', verbose_name='Материал')),
                ('teacher', models.ForeignKey(db_column='teacher_id', on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='teachers.teacher', verbose_name='Педагог')),
            ],
            options={
                'verbose_name': 'Избранный материал',
                'verbose_name_plural': 'Избранные материалы',
                'db_table': 'favorite',
                'unique_together': {('teacher', 'material')},
            },
        ),
    ]
