# Generated by Django 6.0.1 on 2026-02-26 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0002_alter_news_options_alter_newsphoto_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор типа активности')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип активности',
                'verbose_name_plural': 'Типы активности',
                'db_table': 'activity_type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EventFormat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор формата проведения')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Формат проведения',
                'verbose_name_plural': 'Форматы проведения',
                'db_table': 'event_format',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор предметной области')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Предметная область',
                'verbose_name_plural': 'Предметные области',
                'db_table': 'subject',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор мероприятия')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('short_description', models.CharField(max_length=250, verbose_name='Краткое описание')),
                ('detailed_description', models.TextField(max_length=3000, verbose_name='Подробное описание')),
                ('date', models.DateField(verbose_name='Дата проведения')),
                ('time', models.TimeField(verbose_name='Время проведения')),
                ('location', models.CharField(max_length=100, verbose_name='Место проведения')),
                ('participants', models.PositiveIntegerField(default=0, verbose_name='Участников')),
                ('max_participants', models.PositiveIntegerField(default=100, verbose_name='Макс. участников')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('activity_type', models.ForeignKey(db_column='activity_type_id', on_delete=django.db.models.deletion.PROTECT, to='events.activitytype', verbose_name='Тип активности')),
                ('target_audience', models.ForeignKey(db_column='target_audience_id', on_delete=django.db.models.deletion.PROTECT, to='news.targetaudience', verbose_name='Целевая аудитория')),
                ('format', models.ForeignKey(db_column='format_id', on_delete=django.db.models.deletion.PROTECT, to='events.eventformat', verbose_name='Формат проведения')),
                ('subject', models.ForeignKey(db_column='subject_id', on_delete=django.db.models.deletion.PROTECT, to='events.subject', verbose_name='Предметная область')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
                'db_table': 'event',
                'ordering': ['-date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='EventPhoto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор фото')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='events/photos/', verbose_name='Фотография')),
                ('event', models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='events.event', verbose_name='Мероприятие')),
            ],
            options={
                'verbose_name': 'Фотография мероприятия',
                'verbose_name_plural': 'Фотографии мероприятий',
                'db_table': 'event_photo',
            },
        ),
    ]
