# Generated by Django 6.0.1 on 2026-03-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='detailed_description',
            field=models.TextField(max_length=5000, verbose_name='Подробное описание'),
        ),
    ]
