# Generated by Django 6.0.1 on 2026-02-26 11:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор типа контента')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип контента',
                'verbose_name_plural': 'Типы контента',
                'db_table': 'content_type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InfoStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор статуса информации')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Статус информации',
                'verbose_name_plural': 'Статусы информации',
                'db_table': 'info_status',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TargetAudience',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор целевой аудитории')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Целевая аудитория',
                'verbose_name_plural': 'Целевые аудитории',
                'db_table': 'target_audience',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор новости')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('short_description', models.CharField(max_length=250, verbose_name='Краткое описание')),
                ('detailed_description', models.TextField(max_length=3000, verbose_name='Подробное описание')),
                ('publication_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('content_type', models.ForeignKey(db_column='content_type_id', on_delete=django.db.models.deletion.PROTECT, to='news.contenttype', verbose_name='Тип контента')),
                ('info_status', models.ForeignKey(db_column='info_status_id', on_delete=django.db.models.deletion.PROTECT, to='news.infostatus', verbose_name='Статус информации')),
                ('target_audience', models.ForeignKey(db_column='target_audience_id', on_delete=django.db.models.deletion.PROTECT, to='news.targetaudience', verbose_name='Целевая аудитория')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'db_table': 'news',
                'ordering': ['-publication_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsPhoto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор фото')),
                ('photo', models.CharField(max_length=100, verbose_name='Путь к файлу')),
                ('news', models.ForeignKey(db_column='news_id', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='news.news', verbose_name='Новость')),
            ],
            options={
                'verbose_name': 'Фотография новости',
                'verbose_name_plural': 'Фотографии новостей',
                'db_table': 'news_photo',
            },
        ),
    ]
