# Generated by Django 6.0.1 on 2026-02-26 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-publication_date'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterField(
            model_name='newsphoto',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='news/photos/', verbose_name='Фотография'),
        ),
    ]
