# Generated by Django 6.0.1 on 2026-03-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_options_alter_newsphoto_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='detailed_description',
            field=models.TextField(max_length=5000, verbose_name='Подробное описание'),
        ),
    ]
