# Generated by Django 6.0.1 on 2026-02-27 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор дополнительной категории')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Дополнительная категория',
                'verbose_name_plural': 'Дополнительные категории',
                'db_table': 'additional_category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentSystem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор системы оценивания')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Система оценивания',
                'verbose_name_plural': 'Системы оценивания',
                'db_table': 'assessment_system',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DifficultyLevel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор уровня сложности')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Уровень сложности',
                'verbose_name_plural': 'Уровни сложности',
                'db_table': 'difficulty_level',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор класса')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
                'db_table': 'grade',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор типа материала')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('bg_color', models.CharField(default='rgba(201, 228, 202, 0.85)', max_length=50, verbose_name='Цвет фона')),
                ('text_color', models.CharField(default='#1e5128', max_length=50, verbose_name='Цвет текста')),
            ],
            options={
                'verbose_name': 'Тип материала',
                'verbose_name_plural': 'Типы материалов',
                'db_table': 'material_type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор предметной области')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('bg_color', models.CharField(default='rgba(184, 212, 232, 0.85)', max_length=50, verbose_name='Цвет фона')),
                ('text_color', models.CharField(default='#0c4a6e', max_length=50, verbose_name='Цвет текста')),
            ],
            options={
                'verbose_name': 'Предметная область',
                'verbose_name_plural': 'Предметные области',
                'db_table': 'materials_subject',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkFormat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор формата работы')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Формат работы',
                'verbose_name_plural': 'Форматы работы',
                'db_table': 'work_format',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор материала')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.CharField(max_length=250, verbose_name='Описание')),
                ('file', models.FileField(blank=True, null=True, upload_to='materials/', verbose_name='Файл')),
                ('duration', models.CharField(default='45 минут', max_length=50, verbose_name='Длительность')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('additional', models.ForeignKey(db_column='additional_id', on_delete=django.db.models.deletion.PROTECT, to='materials.additionalcategory', verbose_name='Дополнительная категория')),
                ('assessment', models.ForeignKey(db_column='assessment_id', on_delete=django.db.models.deletion.PROTECT, to='materials.assessmentsystem', verbose_name='Система оценки')),
                ('difficulty', models.ForeignKey(db_column='difficulty_id', on_delete=django.db.models.deletion.PROTECT, to='materials.difficultylevel', verbose_name='Уровень сложности')),
                ('grade', models.ForeignKey(db_column='grade_id', on_delete=django.db.models.deletion.PROTECT, to='materials.grade', verbose_name='Класс')),
                ('material_type', models.ForeignKey(db_column='material_type_id', on_delete=django.db.models.deletion.PROTECT, to='materials.materialtype', verbose_name='Тип материала')),
                ('subject', models.ForeignKey(db_column='subject_id', on_delete=django.db.models.deletion.PROTECT, to='materials.subject', verbose_name='Предметная область')),
                ('format', models.ForeignKey(db_column='format_id', on_delete=django.db.models.deletion.PROTECT, to='materials.workformat', verbose_name='Формат работы')),
            ],
            options={
                'verbose_name': 'Методический материал',
                'verbose_name_plural': 'Методические материалы',
                'db_table': 'material',
                'ordering': ['-created_at'],
            },
        ),
    ]
