# Generated by Django 6.0.1 on 2026-06-08 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='additional',
            field=models.ForeignKey(blank=True, db_column='additional_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='materials.additionalcategory', verbose_name='Дополнительная категория'),
        ),
    ]
