# Generated by Django 6.0.1 on 2026-03-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответов',
                'db_table': 'answer_option',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'db_table': 'question',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'Опросы',
                'db_table': 'survey',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SurveyPassing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Прохождение опроса',
                'verbose_name_plural': 'Прохождения опросов',
                'db_table': 'survey_passing',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeacherAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Ответ педагога',
                'verbose_name_plural': 'Ответы педагогов',
                'db_table': 'teacher_answer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('short_description', models.TextField(verbose_name='Краткое описание')),
                ('full_description', models.TextField(verbose_name='Подробное описание')),
                ('date_time', models.DateTimeField(verbose_name='Дата и время проведения')),
                ('location', models.CharField(max_length=300, verbose_name='Место проведения')),
                ('subject_area', models.CharField(choices=[('biology', 'Биология'), ('geography', 'География'), ('preschool', 'Дошкольное образование'), ('art', 'ИЗО'), ('foreign_languages', 'Иностранные языки'), ('informatics', 'Информатика'), ('history', 'История'), ('math', 'Математика'), ('interdisciplinary', 'Межпредметные направления'), ('music', 'Музыка'), ('elementary', 'Начальные классы'), ('social_studies', 'Обществознание'), ('russian', 'Русский язык и литература'), ('physics', 'Физика'), ('physical_education', 'Физическая культура'), ('chemistry', 'Химия'), ('all', 'Подходит всем')], max_length=30, verbose_name='Предметная область')),
                ('format', models.CharField(choices=[('offline', 'Очные мероприятия (оффлайн)'), ('online', 'Дистанционные мероприятия (онлайн)'), ('hybrid', 'Гибридные форматы')], max_length=20, verbose_name='Формат проведения')),
                ('activity_type', models.CharField(choices=[('webinar', 'Вебинар'), ('competition', 'Конкурс'), ('conference', 'Конференция'), ('round_table', 'Круглый стол'), ('training_courses', 'Курсы повышения квалификации'), ('master_class', 'Мастер-класс'), ('olympiad', 'Олимпиада'), ('open_lesson', 'Открытый урок'), ('seminar', 'Семинар'), ('meeting', 'Слет'), ('training', 'Тренинг'), ('forum', 'Форум')], max_length=30, verbose_name='Тип активности')),
                ('target_audience', models.CharField(choices=[('beginner', 'Начинающие педагоги (0-1 год)'), ('experienced_young', 'Опытные молодые специалисты (1-3 года)'), ('mentors', 'Педагоги-наставники'), ('leaders', 'Руководители методических объединений')], max_length=30, verbose_name='Целевая аудитория')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='MethodMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('short_description', models.TextField(verbose_name='Краткое описание')),
                ('subject_area', models.CharField(choices=[('biology', 'Биология'), ('geography', 'География'), ('preschool', 'Дошкольное образование'), ('art_music', 'ИЗО и музыка'), ('foreign_languages', 'Иностранные языки'), ('informatics', 'Информатика и ИКТ'), ('history_social', 'История и обществознание'), ('math', 'Математика'), ('elementary', 'Начальные классы'), ('safety', 'ОБЖ'), ('russian', 'Русский язык и литература'), ('technology', 'Технология'), ('physics', 'Физика'), ('physical_education', 'Физическая культура'), ('chemistry', 'Химия')], max_length=30, verbose_name='Предметная область')),
                ('material_type', models.CharField(choices=[('audio', 'Аудиоматериалы'), ('video', 'Видеоуроки'), ('didactic', 'Дидактические материалы'), ('interactive', 'Интерактивные задания'), ('lesson_plans', 'Конспекты уроков'), ('lab_works', 'Лабораторные работы'), ('practicums', 'Практикумы'), ('presentations', 'Презентации'), ('handouts', 'Раздаточные материалы'), ('lesson_scenarios', 'Сценарии уроков'), ('tests', 'Тесты и контрольные работы'), ('creative_projects', 'Творческие проекты')], max_length=30, verbose_name='Тип материала')),
                ('difficulty_level', models.CharField(choices=[('basic', 'Базовый уровень'), ('gifted', 'Задания для одаренных детей'), ('inclusive', 'Инклюзивное образование'), ('correctional', 'Коррекционные задания'), ('advanced', 'Продвинутый уровень'), ('deep', 'Углубленное изучение')], max_length=30, verbose_name='Уровень сложности')),
                ('grade', models.CharField(choices=[('1-4', '1-4 классы'), ('5-6', '5-6 классы'), ('7-9', '7-9 классы'), ('10-11', '10-11 классы'), ('preschool', 'Дошкольное образование'), ('vocational', 'Среднее профессиональное образование')], max_length=15, verbose_name='Класс')),
                ('work_format', models.CharField(choices=[('group', 'Групповая работа'), ('distance', 'Дистанционное обучение'), ('individual', 'Индивидуальная работа'), ('pair', 'Парная работа'), ('project', 'Проектная деятельность'), ('blended', 'Смешанное обучение'), ('frontal', 'Фронтальная работа')], max_length=30, verbose_name='Формат работы')),
                ('assessment_system', models.CharField(choices=[('point', 'С балльной системой'), ('peer', 'С взаимопроверкой'), ('criteria', 'С критериальным оцениванием'), ('self', 'С самооценкой'), ('pass_fail', 'С системой зачет/незачет')], max_length=30, verbose_name='Система оценки')),
                ('additional_category', models.CharField(choices=[('author_methods', 'Авторские методики'), ('extracurricular', 'Внеурочная деятельность'), ('holiday', 'К праздничным датам'), ('local_history', 'Краеведческие материалы'), ('substitute', 'Материалы для замены уроков'), ('olympiad_prep', 'Подготовка к олимпиадам'), ('exam_prep', 'Подготовка к экзаменам'), ('career_guidance', 'Профориентационные уроки'), ('seasonal', 'Сезонные материалы'), ('experimental', 'Экспериментальные разработки')], max_length=30, verbose_name='Дополнительная категория')),
                ('file', models.FileField(upload_to='materials/', verbose_name='Файл материала')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Методический материал',
                'verbose_name_plural': 'Методические материалы',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('short_description', models.TextField(verbose_name='Краткое описание')),
                ('full_description', models.TextField(verbose_name='Подробное описание')),
                ('publish_date', models.DateField(verbose_name='Дата публикации')),
                ('status', models.CharField(choices=[('emergency', 'Экстренные'), ('important', 'Важные'), ('news', 'Новости'), ('analytics', 'Аналитика'), ('announcements', 'Анонсы'), ('documents', 'Документы'), ('reports', 'Отчеты'), ('recommendations', 'Рекомендации')], max_length=20, verbose_name='Статус информации')),
                ('content_type', models.CharField(choices=[('grants', 'Гранты и финансирование'), ('science', 'Наука и исследования'), ('training', 'Повышение квалификации'), ('social_support', 'Социальная поддержка'), ('creativity', 'Творчество и проекты'), ('regulations', 'Нормативные документы')], max_length=30, verbose_name='Тип контента')),
                ('target_audience', models.CharField(choices=[('mentors', 'Наставники'), ('administration', 'Администрация'), ('young_teachers', 'Молодые педагоги'), ('all_teachers', 'Все педагоги'), ('class_leaders', 'Классные руководители'), ('subject_teachers', 'Предметники')], max_length=30, verbose_name='Целевая аудитория')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='NormativeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('short_description', models.TextField(verbose_name='Краткое описание')),
                ('publish_date', models.DateField(verbose_name='Дата публикации')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Размер файла (в КБ)')),
                ('category', models.CharField(choices=[('fgos', 'ФГОС'), ('federal_laws', 'Федеральные законы'), ('orders', 'Приказы'), ('method_recommendations', 'Методические рекомендации'), ('prof_standards', 'Профстандарты'), ('local_acts', 'Локальные акты'), ('sanitary_norms', 'Санитарные нормы')], max_length=30, verbose_name='Категория')),
                ('action_level', models.CharField(choices=[('federal', 'Федеральный'), ('regional', 'Региональный'), ('local', 'Локальный')], max_length=20, verbose_name='Уровень действия')),
                ('document_year', models.CharField(blank=True, choices=[('2024', '2024'), ('2023', '2023'), ('2022', '2022'), ('2021', '2021'), ('2020_earlier', '2020 и ранее')], max_length=15, null=True, verbose_name='Год документа')),
                ('file', models.FileField(upload_to='documents/', verbose_name='Файл документа')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Нормативный документ',
                'verbose_name_plural': 'Нормативные документы',
            },
        ),
    ]
