# Generated by Django 6.0.1 on 2026-03-07 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'managed': False, 'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
        migrations.AlterModelOptions(
            name='methodmaterial',
            options={'managed': False, 'verbose_name': 'Методический материал', 'verbose_name_plural': 'Методические материалы'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'managed': False, 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='normativedocument',
            options={'managed': False, 'verbose_name': 'Нормативный документ', 'verbose_name_plural': 'Нормативные документы'},
        ),
    ]
