# Generated by Django 6.0.1 on 2026-03-07 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_alter_event_options_alter_methodmaterial_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Статус активности',
                'verbose_name_plural': 'Статусы активности',
                'db_table': 'activity_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Тип вопроса',
                'verbose_name_plural': 'Типы вопросов',
                'db_table': 'question_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SurveyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Категория опроса',
                'verbose_name_plural': 'Категории опросов',
                'db_table': 'survey_category',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='SurveyPassing',
        ),
        migrations.DeleteModel(
            name='TeacherAnswer',
        ),
        migrations.AlterModelTable(
            name='event',
            table='event',
        ),
        migrations.AlterModelTable(
            name='methodmaterial',
            table='material',
        ),
        migrations.AlterModelTable(
            name='news',
            table='news',
        ),
        migrations.AlterModelTable(
            name='normativedocument',
            table='document',
        ),
    ]
