# Generated by Django 6.0.1 on 2026-06-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_adminuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminuser',
            name='username',
        ),
        migrations.AddField(
            model_name='adminuser',
            name='email',
            field=models.EmailField(default='temp@admin.ru', max_length=200, unique=True, verbose_name='Email (логин)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Имя администратора'),
        ),
    ]
