# Generated by Django 6.0.1 on 2026-06-08 16:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('icon', models.CharField(default='fas fa-star', max_length=50, verbose_name='Иконка')),
                ('icon_color', models.CharField(default='#3b82f6', max_length=20, verbose_name='Цвет иконки')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Категория практики',
                'verbose_name_plural': 'Категории практик',
                'db_table': 'practice_category',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('short_description', models.CharField(max_length=250, verbose_name='Краткое описание')),
                ('full_description', models.TextField(blank=True, verbose_name='Полное описание')),
                ('audience', models.CharField(blank=True, choices=[('young', 'Молодые педагоги (до 3 лет)'), ('experienced', 'Опытные педагоги'), ('all', 'Все категории')], max_length=20, verbose_name='Целевая аудитория')),
                ('format_type', models.CharField(blank=True, choices=[('single', 'Опыт одного педагога'), ('methodological', 'Опыт методического объединения'), ('school', 'Школьный проект'), ('municipal', 'Муниципальный опыт'), ('regional', 'Региональный опыт')], max_length=20, verbose_name='Формат практики')),
                ('difficulty', models.CharField(blank=True, choices=[('easy', 'Лёгкий'), ('medium', 'Средний'), ('hard', 'Сложный')], max_length=10, verbose_name='Уровень сложности')),
                ('file', models.FileField(blank=True, null=True, upload_to='practices/files/', verbose_name='Файл')),
                ('created_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='practices', to='success_practices.practicecategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Успешная практика',
                'verbose_name_plural': 'Успешные практики',
                'db_table': 'practice',
                'ordering': ['-created_date'],
            },
        ),
    ]
