# Generated by Django 6.0.1 on 2026-06-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('success_practices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='audience',
            field=models.CharField(choices=[('young', 'Молодые педагоги (до 3 лет)'), ('experienced', 'Опытные педагоги'), ('all', 'Все категории')], max_length=20, verbose_name='Целевая аудитория'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Лёгкий'), ('medium', 'Средний'), ('hard', 'Сложный')], max_length=10, verbose_name='Уровень сложности'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='format_type',
            field=models.CharField(choices=[('single', 'Опыт одного педагога'), ('methodological', 'Опыт методического объединения'), ('school', 'Школьный проект'), ('municipal', 'Муниципальный опыт'), ('regional', 'Региональный опыт')], max_length=20, verbose_name='Формат практики'),
        ),
    ]
