# Generated by Django 6.0.1 on 2026-06-08 17:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('success_practices', '0002_alter_practice_audience_alter_practice_difficulty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='audience',
            field=models.CharField(choices=[('young', 'Молодые педагоги (до 3 лет)'), ('experienced', 'Опытные педагоги'), ('all', 'Все категории')], db_index=True, max_length=20, verbose_name='Целевая аудитория'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='created_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Лёгкий'), ('medium', 'Средний'), ('hard', 'Сложный')], db_index=True, max_length=10, verbose_name='Уровень сложности'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='format_type',
            field=models.CharField(choices=[('single', 'Опыт одного педагога'), ('methodological', 'Опыт методического объединения'), ('school', 'Школьный проект'), ('municipal', 'Муниципальный опыт'), ('regional', 'Региональный опыт')], db_index=True, max_length=20, verbose_name='Формат практики'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Опубликовано'),
        ),
        migrations.AddIndex(
            model_name='practice',
            index=models.Index(fields=['is_published', '-created_date'], name='practice_is_publ_5763ba_idx'),
        ),
        migrations.AddIndex(
            model_name='practice',
            index=models.Index(fields=['category', 'is_published'], name='practice_categor_78aaeb_idx'),
        ),
    ]
