# Generated by Django 6.0.1 on 2026-02-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор педагога')),
                ('email', models.CharField(max_length=30, unique=True, verbose_name='Email')),
                ('password', models.CharField(max_length=128, verbose_name='Пароль')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Отчество')),
                ('experience', models.IntegerField(blank=True, null=True, verbose_name='Педагогический стаж')),
                ('category', models.CharField(blank=True, max_length=50, null=True, verbose_name='Квалификационная категория')),
                ('specialization', models.CharField(blank=True, max_length=50, null=True, verbose_name='Предметная специализация')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teachers/', verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Педагог',
                'verbose_name_plural': 'Педагоги',
                'db_table': 'teacher',
            },
        ),
    ]
