# Generated by Django 6.0.1 on 2026-06-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='educational_institution',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Образовательное учреждение'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='specializations',
            field=models.TextField(blank=True, null=True, verbose_name='Предметные специализации (множественный выбор)'),
        ),
    ]
