# Generated by Django 6.0.1 on 2026-02-27 17:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLevel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор уровня действия')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Уровень действия',
                'verbose_name_plural': 'Уровни действия',
                'db_table': 'action_level',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор категории документа')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('bg_color', models.CharField(default='rgba(184, 212, 232, 0.85)', max_length=50, verbose_name='Цвет фона')),
                ('text_color', models.CharField(default='#0c4a6e', max_length=50, verbose_name='Цвет текста')),
            ],
            options={
                'verbose_name': 'Категория документа',
                'verbose_name_plural': 'Категории документов',
                'db_table': 'document_category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор документа')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.CharField(max_length=250, verbose_name='Краткое описание')),
                ('publication_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('file_size', models.IntegerField(default=0, verbose_name='Размер файла (в байтах)')),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Файл документа')),
                ('online_url', models.URLField(blank=True, verbose_name='Ссылка для онлайн просмотра')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('level', models.ForeignKey(db_column='level_id', on_delete=django.db.models.deletion.PROTECT, to='documents.actionlevel', verbose_name='Уровень действия')),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.PROTECT, to='documents.documentcategory', verbose_name='Категория документа')),
            ],
            options={
                'verbose_name': 'Нормативный документ',
                'verbose_name_plural': 'Нормативные документы',
                'db_table': 'document',
                'ordering': ['-publication_date'],
            },
        ),
    ]
