# Generated by Django 6.0.1 on 2026-02-27 18:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор статуса активности')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Статус активности',
                'verbose_name_plural': 'Статусы активности',
                'db_table': 'activity_status',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор вопроса')),
                ('text', models.CharField(max_length=300, verbose_name='Текст вопроса')),
                ('order', models.PositiveIntegerField(verbose_name='Порядок следования')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'db_table': 'question',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор типа вопроса')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип вопроса',
                'verbose_name_plural': 'Типы вопросов',
                'db_table': 'question_type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SurveyCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор категории опроса')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('bg_color', models.CharField(default='rgba(201, 228, 202, 0.85)', max_length=50, verbose_name='Цвет фона')),
                ('text_color', models.CharField(default='#1e5128', max_length=50, verbose_name='Цвет текста')),
            ],
            options={
                'verbose_name': 'Категория опроса',
                'verbose_name_plural': 'Категории опросов',
                'db_table': 'survey_category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор ответа')),
                ('text', models.CharField(max_length=200, verbose_name='Текст ответа')),
                ('order', models.PositiveIntegerField(verbose_name='Порядок отображения')),
                ('question', models.ForeignKey(db_column='question_id', on_delete=django.db.models.deletion.CASCADE, related_name='options', to='surveys.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответов',
                'db_table': 'answer_option',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.ForeignKey(db_column='question_type_id', on_delete=django.db.models.deletion.PROTECT, to='surveys.questiontype', verbose_name='Тип вопроса'),
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор опроса')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.CharField(max_length=250, verbose_name='Описание')),
                ('created_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('duration', models.CharField(default='10-15 мин', max_length=20, verbose_name='Время прохождения')),
                ('questions_count', models.PositiveIntegerField(default=0, verbose_name='Количество вопросов')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('status', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.PROTECT, to='surveys.activitystatus', verbose_name='Статус активности')),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.PROTECT, to='surveys.surveycategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'Опросы',
                'db_table': 'survey',
                'ordering': ['-created_date'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(db_column='survey_id', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='surveys.survey', verbose_name='Опрос'),
        ),
        migrations.CreateModel(
            name='SurveyPassing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор прохождения')),
                ('status', models.CharField(default='started', max_length=30, verbose_name='Статус прохождения')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата начала')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('survey', models.ForeignKey(db_column='survey_id', on_delete=django.db.models.deletion.CASCADE, to='surveys.survey', verbose_name='Опрос')),
                ('teacher', models.ForeignKey(db_column='teacher_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Педагог')),
            ],
            options={
                'verbose_name': 'Прохождение опроса',
                'verbose_name_plural': 'Прохождения опросов',
                'db_table': 'survey_passing',
            },
        ),
        migrations.CreateModel(
            name='TeacherAnswer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор ответа педагога')),
                ('text_answer', models.CharField(blank=True, max_length=300, verbose_name='Текст ответа')),
                ('answer_option', models.ForeignKey(blank=True, db_column='answer_option_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.answeroption', verbose_name='Вариант ответа')),
                ('passing', models.ForeignKey(db_column='passing_id', on_delete=django.db.models.deletion.CASCADE, to='surveys.surveypassing', verbose_name='Прохождение')),
                ('question', models.ForeignKey(db_column='question_id', on_delete=django.db.models.deletion.CASCADE, to='surveys.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Ответ педагога',
                'verbose_name_plural': 'Ответы педагогов',
                'db_table': 'teacher_answer',
            },
        ),
    ]
