# Generated by Django 6.0.1 on 2026-03-07 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teacheranswer',
            unique_together={('passing', 'question')},
        ),
        migrations.AddField(
            model_name='question',
            name='is_required',
            field=models.BooleanField(default=True, verbose_name='Обязательный вопрос'),
        ),
        migrations.AddField(
            model_name='teacheranswer',
            name='selected_option',
            field=models.ForeignKey(blank=True, db_column='selected_option_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='single_answers', to='surveys.answeroption', verbose_name='Выбранный вариант'),
        ),
        migrations.AddField(
            model_name='teacheranswer',
            name='selected_options',
            field=models.ManyToManyField(blank=True, related_name='multiple_answers', to='surveys.answeroption', verbose_name='Выбранные варианты'),
        ),
        migrations.AlterField(
            model_name='surveypassing',
            name='status',
            field=models.CharField(choices=[('started', 'Начат'), ('in_progress', 'В процессе'), ('completed', 'Завершен')], default='started', max_length=20, verbose_name='Статус прохождения'),
        ),
        migrations.AlterField(
            model_name='surveypassing',
            name='survey',
            field=models.ForeignKey(db_column='survey_id', on_delete=django.db.models.deletion.CASCADE, related_name='passings', to='surveys.survey', verbose_name='Опрос'),
        ),
        migrations.AlterField(
            model_name='surveypassing',
            name='teacher',
            field=models.ForeignKey(db_column='teacher_id', on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher', verbose_name='Педагог'),
        ),
        migrations.AlterField(
            model_name='teacheranswer',
            name='passing',
            field=models.ForeignKey(db_column='passing_id', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.surveypassing', verbose_name='Прохождение'),
        ),
        migrations.AlterField(
            model_name='teacheranswer',
            name='text_answer',
            field=models.TextField(blank=True, max_length=5000, verbose_name='Текстовый ответ'),
        ),
        migrations.AlterUniqueTogether(
            name='surveypassing',
            unique_together={('survey', 'teacher')},
        ),
        migrations.RemoveField(
            model_name='teacheranswer',
            name='answer_option',
        ),
    ]
