# Generated by Django 6.0.1 on 2026-03-07 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_alter_teacheranswer_unique_together_and_more'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='surveypassing',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='surveypassing',
            name='teacher',
            field=models.ForeignKey(blank=True, db_column='teacher_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher', verbose_name='Педагог'),
        ),
    ]
